stages:
  - build
  - release

cache:
  paths:
    - node_modules/

build_packagedev:
  image: node
  stage: build
  only:
    - tags
  before_script:
    - apt-get update
    - apt-get install -y libx11-dev libxkbfile-dev libsecret-1-dev
    - dpkg --add-architecture i386
    - apt-get update
    - apt-get install -y wine64 wine32
  script:
    - yarn install
    - yarn release:win
    - yarn release:linux
  artifacts:
    paths:
      - dist/
    expire_in: 4 weeks

release:
  stage: release
  only:
    - tags
  image: curlimages/curl:latest
  script:
    - echo "Uploading artifacts to GitLab release..."
    - |
      for file in dist/*; do
        filename=$(basename "$file" | sed 's/ /%20/g')
        echo "Uploading $file..."
        UPLOAD_URL="https://git.nosi.cv/api/v4/projects/${CI_PROJECT_ID}/packages/generic/electron-builder/${CI_COMMIT_TAG}/$(basename "$file")"
        echo "Upload URL: $UPLOAD_URL"
        
        if [[ -n "${GITLAB_TOKEN}" && -n "${CI_PROJECT_ID}" && -n "${CI_COMMIT_TAG}" ]]; then
          curl --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
               --upload-file "$file" \
               "$UPLOAD_URL"
        else
          echo "Error: Missing required environment variables."
          exit 1
        fi
      done

    - echo "Creating a new release on GitLab..."
    - |
      curl --request POST \
           --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
           --header "Content-Type: application/json" \
           --data "{
             \"name\": \"Release ${CI_COMMIT_TAG}\",
             \"tag_name\": \"${CI_COMMIT_TAG}\",
             \"description\": \"Release for commit ${CI_COMMIT_SHA}\",
             \"assets\": {
               \"links\": [
                 {
                   \"name\": \"Download\",
                   \"url\": \"https://git.nosi.cv/api/v4/projects/${CI_PROJECT_ID}/packages/generic/electron-builder/${CI_COMMIT_TAG}\"
                 }
               ]
             }
           }" \
           "https://git.nosi.cv/api/v4/projects/${CI_PROJECT_ID}/releases"

  needs:
    - build_packagedev
