import { configureStore } from '@reduxjs/toolkit'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import React, { type JSX, useEffect, useState } from 'react'
import { Provider } from 'react-redux'
import { ActiveThemeProvider } from './components/active-theme-provider'
import { ThemeProvider } from './components/theme-provider'
import { ProcessStudioClientProvider } from './features/bpmn'
import { EngineCatalogProvider } from './features/engine-catalog'
import { useIgrpCliUpdateCheck } from './hooks/useIgrpCliUpdateCheck'
import rootReducer from './redux'
import { subscribeToSpecDataChunks } from './redux/specData/thunks'
import { subscribeDocsChanged } from './redux/specDocs/thunks'
import { subscribeKBProgress } from './redux/specKB/thunks'
import { subscribePrototypeEvents } from './redux/specPrototype/thunks'
import AppRoutes from './routes/Routes'
import { ThemeService } from './services/ThemeService'

import '@igrp/framework-process-studio-bpmn-editor/dist/styles.css'

// DS styles are now generated by the app's Tailwind (see globals.css @source +
// tokens import). v0.1.0-beta.141 removed the precompiled `/styles` export.
import { Toaster } from '@renderer/components/ui/sonner'
// Configure Redux store
// serializableCheck/immutableCheck deep-scan the *whole* tree on every
// dispatch. A few slices are known-large, already-plain (strings/JSON) data
// that don't need the safety net but do pay its traversal cost on every
// single dispatch, project-wide:
// - specDocs.byDoc: full editor buffers, dispatched on every keystroke.
// - specPrototypeManifest.manifest: full generated-page component tree,
//   mutated on every canvas edit.
// - PageBuilder.filesThree: recursive `.igrpstudio/` file tree, reloaded via
//   getFileThree() whenever Page Builder opens/refreshes.
// Everything else stays checked.
const IGNORED_STATE_PATHS = [
    /^specDocs\.byDoc/,
    /^specPrototypeManifest\.manifest/,
    /^PageBuilder\.filesThree/
]
const store = configureStore({
    reducer: rootReducer,
    devTools: true,
    middleware: (getDefaultMiddleware) =>
        getDefaultMiddleware({
            serializableCheck: { ignoredPaths: IGNORED_STATE_PATHS },
            immutableCheck: { ignoredPaths: IGNORED_STATE_PATHS }
        })
})

// TanStack Query client — scoped usage (BPMN module). Defaults from §4.5 of the
// process-integration plan: read queries are reasonably fresh.
const queryClient = new QueryClient({
    defaultOptions: {
        queries: {
            staleTime: 30_000,
            refetchOnWindowFocus: false
        }
    }
})

// Subscribe once to spec:kb progress events so KB items refresh in real time.
if (typeof window !== 'undefined' && (window as any).specKB) {
    subscribeKBProgress()(store.dispatch)
}

// Subscribe once to spec:doc changes so the documents tree refreshes when the
// backend reports mutations from any source.
if (typeof window !== 'undefined' && (window as any).specDoc) {
    subscribeDocsChanged(() => store.getState().PageBuilder.basePath)(store.dispatch)
}

// Subscribe once to prototype dev-server logs/status events.
if (typeof window !== 'undefined' && (window as any).specPrototype) {
    subscribePrototypeEvents()(store.dispatch)
}

// Subscribe once to spec:data generator chunks so the chat snapshot card
// + per-turn applied/failed counts land in the specData slice.
if (typeof window !== 'undefined' && (window as any).specData) {
    subscribeToSpecDataChunks(store.dispatch)
}

/** Runs CLI update checks inside the Redux + i18n tree. */
function IgrpCliUpdateWatcher(): null {
    useIgrpCliUpdateCheck()
    return null
}

const App = (): JSX.Element => {
    const [activeThemeValue, setActiveThemeValue] = useState<string>('igrp')

    useEffect(() => {
        async function loadTheme(): Promise<void> {
            const savedTheme = await ThemeService.getActiveTheme()
            if (savedTheme) {
                setActiveThemeValue(savedTheme)
            }
        }

        loadTheme()
    }, [])

    return (
        <Provider store={store}>
            <QueryClientProvider client={queryClient}>
                <ProcessStudioClientProvider>
                    <EngineCatalogProvider>
                        <React.Fragment>
                            <ThemeProvider defaultTheme="system" storageKey="vite-ui-theme">
                                <ActiveThemeProvider initialTheme={activeThemeValue}>
                                    <IgrpCliUpdateWatcher />
                                    <Toaster richColors closeButton expand />
                                    <AppRoutes />
                                </ActiveThemeProvider>
                            </ThemeProvider>
                        </React.Fragment>
                    </EngineCatalogProvider>
                </ProcessStudioClientProvider>
            </QueryClientProvider>
        </Provider>
    )
}

export default App
