/**
 * Shared map of IGRP component name → lucide icon.
 *
 * Keys are the string identifiers the engine emits (matching the `COMPONENT`
 * enum's *values* in `generators/ui/ComponentTypes.ts`). Decoupling the keys
 * from that enum keeps this module independent of the UI generator — anyone
 * holding a `componentName: string` (the Prototype palette, the API generator,
 * future surfaces) can look up the right icon without depending on
 * `generators/ui`.
 */

import {
    Activity,
    AlignLeft,
    AreaChart,
    ArrowLeft,
    ArrowRightLeft,
    Badge,
    BarChart2,
    Bell,
    Bell as BellIcon,
    BellRing,
    Donut as ButtonIcon,
    Calendar,
    CalendarClock,
    CalendarDays,
    Calendar as CalendarIcon,
    CaseSensitive,
    ChartBarBig,
    ChartColumnBig,
    CheckCircle,
    CheckSquare,
    ChevronDown,
    ChevronsRight,
    ChevronsUpDown,
    CircleDot,
    CircleUser,
    Clock,
    Code,
    Columns2,
    Command,
    Copy,
    CreditCard,
    Crop,
    DollarSign,
    Dot,
    Edit3,
    Ellipsis,
    Eye,
    EyeOff,
    FileText,
    Fingerprint,
    FormInput as Form,
    FormInput,
    Frame,
    Gauge,
    GitMerge,
    Grid,
    Hash,
    Heading,
    Heading1,
    Heart,
    Image,
    Inbox,
    Info,
    Keyboard,
    Layout,
    LayoutList,
    LayoutTemplate,
    LineChart,
    Link2,
    List,
    ListCollapse,
    List as ListIcon,
    ListOrdered,
    LoaderCircle,
    Map,
    Megaphone,
    Menu,
    MessageCircle,
    MessageSquare,
    MessageSquareText,
    MousePointer2,
    MoveRight,
    Navigation,
    Palette,
    PanelBottom,
    PanelRight,
    PanelTop,
    Phone,
    PieChart,
    Play,
    RadarIcon,
    Ratio,
    RectangleEllipsis,
    RectangleHorizontal,
    Scroll,
    Search,
    SeparatorHorizontal,
    Sliders,
    Square,
    SquareMenu,
    SquareMousePointer,
    Star,
    Table,
    Table2,
    Table as Tabs,
    Text,
    TextCursorInput,
    Text as TextIcon,
    TextQuote,
    ToggleLeft,
    ToggleRight,
    TrendingUp,
    UnfoldVertical,
    Upload,
    Video,
    WrapText
} from 'lucide-react'
import type React from 'react'

/**
 * `componentName` → icon. The key set tracks the `COMPONENT` enum *values*
 * in `generators/ui/ComponentTypes.ts`; when that enum grows, mirror new
 * entries here. Unknown names fall back to a generic icon via
 * `resolveIcon()`.
 */
export const ICON_MAP: Record<string, React.ElementType> = {
    input: TextCursorInput,
    inputText: TextCursorInput,
    inputAddOn: FormInput,
    inputNumber: Hash,
    label: CaseSensitive,
    inputHidden: EyeOff,
    datePicker: Calendar,
    inputDatePicker: Calendar,
    inputTime: Clock,
    inputPassword: Eye,
    inputColor: Palette,
    inputTextarea: AlignLeft,
    inputPhone: Phone,
    inputFile: Upload,
    select: ChevronsUpDown,
    combobox: List,
    checkbox: CheckSquare,
    radio: CircleDot,
    switch: ToggleLeft,
    slider: Sliders,
    inputUrl: Link2,
    button: SquareMousePointer,
    text: Text,
    image: Image,
    richTextEditor: Edit3,
    table: Table,
    chart: BarChart2,
    maps: Map,
    carousel: Play,
    fingerprint: Fingerprint,
    datePickerRange: Calendar,

    panel: Layout,
    card: CreditCard,
    tabs: Tabs,
    list: ListIcon,
    iFrame: Frame,
    infoPanel: Info,
    alerts: Bell,
    badge: Badge,
    ratings: Star,
    videoEmbed: Video,
    progress: Activity,
    calendarSingle: CalendarDays,
    calendarSingleTime: CalendarDays,
    calendarRange: CalendarDays,
    calendarRangeTime: CalendarDays,
    calendarMultiple: CalendarDays,
    calendarMultipleTime: CalendarDays,
    datePickerSingle: Calendar,
    datePickerMultiple: Calendar,
    inputDatePickerSingle: Calendar,

    form: Form,
    container: Square,
    grid: Grid,
    flex: MoveRight,
    columns: Columns2,
    column: Columns2,
    headline: Heading1,
    dropdown: Ellipsis,
    icon: Heart,

    piechart: PieChart,
    areachart: AreaChart,
    linechart: LineChart,
    horizontalBarchart: ChartBarBig,
    verticalBarchart: ChartColumnBig,
    radialBarchart: Gauge,
    radarchart: RadarIcon,

    chat: MessageCircle,
    inputSearch: Search,
    statsCard: TrendingUp,
    separator: SeparatorHorizontal,
    modalDialog: CheckCircle,
    alertDialog: Info,
    aspect: Ratio,
    menuNavigation: Menu,
    alert: Dot,

    pageHeader: Heading,
    fragment: Code,
    paragraph: WrapText,
    textList: WrapText,
    repetitiveList: LayoutList,
    formList: LayoutList,
    infoCard: CreditCard,
    pdfViewer: FileText,
    statusBanner: Bell,

    span: TextIcon,
    section: RectangleHorizontal,

    treeView: GitMerge,

    notifications: BellIcon,

    stack: Table2,

    tableDateFilter: CalendarIcon,
    tableTextFilter: FormInput,
    tableNumberFilter: Sliders,
    tableCheckboxFilter: CheckSquare,
    tableSelectFilter: List,
    tableActionListCell: ButtonIcon,
    tableAmountCell: DollarSign,
    tableCheckboxCell: CheckSquare,
    tableDateCell: CalendarIcon,
    tableTextCell: FormInput,
    tableExpanderCell: ChevronDown,
    tableBadgeCell: Badge,
    tableRowSubcomponent: UnfoldVertical,
    copyTo: Copy,
    avatar: CircleUser,
    // `accordion` previously mapped twice; ListCollapse wins (last-write).
    accordion: ListCollapse,
    cardDetails: ListCollapse,

    // Group A — engine default components now mapped on the canvas.
    command: Command,
    dateTimeInput: CalendarClock,
    loadingSpinner: LoaderCircle,
    notification: Bell,
    pageHeaderBackButton: ArrowLeft,
    statsCardMini: TrendingUp,
    statsCardTopBorderColored: PanelTop,
    toaster: BellRing,
    userAvatar: CircleUser,
    spinner: LoaderCircle,
    scrollArea: Scroll,
    aspectRatio: Ratio,
    skeleton: LayoutTemplate,
    kbd: Keyboard,
    fieldDescription: TextQuote,
    toggle: ToggleRight,
    menubar: SquareMenu,
    popover: MessageSquare,
    hoverCard: MousePointer2,
    sheet: PanelRight,
    drawer: PanelBottom,
    breadcrumb: ChevronsRight,
    pagination: ArrowRightLeft,
    inputOTP: RectangleEllipsis,
    inputGroup: FormInput,
    navigationMenu: Navigation,
    empty: Inbox,
    imageCropper: Crop,
    stepperUI: ListOrdered,
    banner: Megaphone,
    tooltip: MessageSquareText
} as const

/**
 * Fallback icon used when a component name is not registered above.
 * Picked to look distinctly "generic" so missing entries are easy to spot
 * during development.
 */
const FALLBACK_ICON: React.ElementType = Square

/** Resolve an icon by component name, with a sensible default for unknowns. */
export const resolveIcon = (componentName: string | undefined | null): React.ElementType => {
    if (!componentName) return FALLBACK_ICON
    return ICON_MAP[componentName] ?? FALLBACK_ICON
}
