import { IGRPAlertDialog, IGRPAreaChart, IGRPBadge, IGRPButton, IGRPCheckbox, IGRPCombobox, IGRPDataTableFilterDate, IGRPDataTableFilterDropdown, IGRPDataTableFilterFaceted, IGRPDataTableFilterInput, IGRPDataTableFilterMinMax, IGRPDataTableFilterSelect, IGRPDatePicker, IGRPDatePickerRange, IGRPHeadline, IGRPHorizontalBarChart, IGRPIcon, IGRPInputAddOn, IGRPInputColor, IGRPInputFile, IGRPInputNumber, IGRPInputPassword, IGRPInputPhone, IGRPInputSearch, IGRPInputText, IGRPInputTime, IGRPInputUrl, IGRPLabel, IGRPLineChart, IGRPPdfViewer, IGRPPieChart, IGRPRadarChart, IGRPRadialBarChart, IGRPRadioGroup, IGRPSelect, IGRPSeparator, IGRPStatsCard, IGRPStatusBanner, IGRPSwitch, IGRPText, IGRPTextarea, IGRPVerticalBarChart } from '@igrp/igrp-framework-react-design-system';
import {
    Type,
    FormInput,
    Calendar,
    Clock,
    Eye,
    Palette,
    FileText,
    List,
    Upload,
    CheckSquare,
    Radio,
    ToggleLeft,
    Sliders,
    Link2,
    Donut as ButtonIcon,
    Image,
    Edit3,
    Table,
    BarChart2,
    Map,
    Play,
    Fingerprint,
    Layout,
    CreditCard,
    Table as Tabs,
    List as ListIcon,
    Frame,
    Info,
    Calendar as CalendarIcon,
    Bell,
    Badge,
    Star,
    ChevronDown,
    Video,
    Activity,
    AlignLeft,
    GitMerge,
    MessageCircle,
    Bell as BellIcon,
    FormInput as Form,
    Square,
    Grid,
    Columns2,
    Table2,
    RectangleHorizontal,
    Ellipsis,
    DollarSign,
    Heading1,
    Heading,
    Link,
    Phone,
    WrapText,
    LayoutList,
    Code,
    Heart,
    PieChart,
    AreaChart,
    LineChart,
    ChartBarBig,
    ChartColumnBig,
    CaseSensitive,
    Gauge,
    RadarIcon,
    MoveRight,
    Hash,
    EyeOff,
    Search,
    TrendingUp,
    SeparatorHorizontal,
    CheckCircle,
    Ratio,
    Menu,
    Dot,
    Text as TextIcon,
} from 'lucide-react';
import IGRPStudioFlex from './types/components/Flex';
import IGRPStudioGrid from './types/components/Grid';
import IGRPStudioSection from './types/components/Section';
import IGRPStudioColumns from './types/components/Columns';
import IGRPStudioColumn from './types/components/Column';
import IGRPStudioPageHeader from './types/components/PageHeader';
import IGRPStudioForm from './types/components/Form';
import IGRPStudioContainer from './types/components/Container';
import IGRPStudioFragment from './types/components/Fragment';
import IGRPStudioCard from './types/components/Card';
import IGRPStudioPage from './types/components/MainComponent';
import { IGRPStudioDialogDescription, IGRPSTudioDialogFooter, IGRPSTudioDialogHeader, IGRPSTudioDialogTitle, IGRPStudioDialogTrigger, IGRPStudioModalDialog } from './types/components/ModalDialog';
import IGRPStudioTable from './types/components/Table';
import IGRPStudioParagraph from './types/components/Paragraph';
import IGRPStudioTabs from './types/components/Tabs';
import IGRPStudioRepetitive from './types/components/RepetitiveList';
import IGRPStudioMenuNavigation from './types/components/MenuNavigation';
import IGRPStudioFormList from './types/components/FormList';
import IGRPStudioInfoCard from './types/components/InfoCard';
import IGRPStudioAlert from './types/components/Alert';
import IGRPStudioTextList from './types/components/TextList';


// Component Categories
export const GROUP_COMPONET: Record<string, string> = {
    structure: "Structure",
    containers: "Containers",
    formElements: "Form Elements",
    basicElements: "Basic Elements",
    dataDisplay: "Data Display",
    layout: "Layout",
    widget: "Widgets",
    advanced: "Advanced",
    typography: "Typography",
    customComponents: "Custom Components",
    appComponents: 'Application Components'
} as const;

export const COMPONENT: Record<string, string> = {
    ComponentContent: 'component',
    PageContent: "page",
    Columns: "columns",
    Column: "column",
    Grid: "grid",
    Flex: "flex",
    Section: "section",
    Container: 'container',
    Form: 'form',
    PageHeader: 'pageHeader',

    Link: 'inputUrl',
    Button: "button",
    Text: "text",
    Image: "image",
    RichTextEditor: "richTextEditor",
    Table: "table",
    Chart: "chart",
    Maps: "maps",
    Carousel: "carousel",
    Fingerprint: "fingerprint",
    Input: 'input',
    InputText: 'inputText',
    Date: "datePicker",
    DatePicker: 'inputDatePicker',
    TimePicker: 'inputTime',
    Password: "inputPassword",
    Textarea: 'inputTextarea',
    ColorPicker: "inputColor",
    Select: "select",
    Combobox: "combobox",
    AddOn: "inputAddOn",
    Checkbox: "checkbox",
    Radio: "radio",
    Switch: "switch",
    Number: "inputNumber",
    Phone: "inputPhone",
    RangeSlider: "slider",
    FileUpload: "inputFile",
    Hidden: "inputHidden",
    DatePickerRange: "datePickerRange",

    Dropdown: 'dropdown',
    TableColumn: 'tableColumns',
    TableFilter: 'tableFilters',

    TableActionListCell: 'tableActionListCell',
    TableAmountCell: 'tableAmountCell',
    TableCheckboxCell: 'tableCheckboxCell',
    TableDateCell: 'tableDateCell',
    TableableBadgeCell: 'tableBadgeCell',

    TableInputFilter: 'tableInputFilter',
    TableMinMaxFilter: 'tableMinMaxFilter',
    TableFilterDate: 'tableDateFilter',
    TableSelectFilter: 'tableSelectFilter',
    TableFacetedFilter: 'tableFacetedFilter',
    TableFilterDropdown: 'tableDropdownFilter',

    Headline: 'headline',
    Label: 'label',
    Icon: 'icon',

    Box: 'box',
    Panel: 'panel',
    Card: 'card',
    Tabs: 'tabs',

    Badge: 'badge',
    Search: 'inputSearch',

    iFrame: 'iFrame',
    InfoPanel: 'infoPanel',
    Alerts: 'alerts',
    Ratings: 'ratings',

    EmbedVideo: 'embedVideo',

    CardContent: "cardContent",
    CardFooter: "cardFooter",
    CardHeader: "cardHeader",

    Piechart: 'piechart',
    Chat: 'chat',
    Areachart: 'areachart',
    Linechart: 'linechart',
    Barchart: 'barchart',
    HorizontalBarchart: 'horizontalBarchart',
    VerticalBarchart: "verticalBarchart",
    RadialBarchart: "radialBarchart",
    Radarchart: "radarchart",
    StatsCard: "statsCard",
    Separator: "separator",

    ModalDialog: 'modalDialog',
    ModalDialogTitle: "modalDialogTitle",
    ModalDialogTrigger: "modalDialogTrigger",
    ModalDialogHeader: 'modalDialogHeader',
    ModalDialogDescription: "modalDialogDescription",
    ModalDialogContent: "modalDialogContent",
    ModalDialogFooter: "modalDialogFooter",

    AlertDialog: 'alertDialog',
    Aspect: 'aspect',
    Fragment: 'fragment',
    Paragraph: 'paragraph',
    RepetitiveList: 'repetitiveList',
    FormList: 'formList',
    MenuNavigation: 'menuNavigation',
    InfoCard: 'infoCard',
    PdfViewer: 'pdfViewer',
    Alert: 'alert',
    TextList: 'textList',
    StatusBanner: "statusBanner",
    Span: "span"

} as const;


// Icon Mapping
export const ICON_MAP: Record<string, React.ElementType> = {
    [COMPONENT.Input]: FormInput,
    [COMPONENT.InputText]: FormInput,
    [COMPONENT.AddOn]: FormInput,
    [COMPONENT.Number]: Hash,
    [COMPONENT.Label]: CaseSensitive,
    [COMPONENT.Hidden]: EyeOff,
    [COMPONENT.Date]: Calendar,
    [COMPONENT.DatePicker]: Calendar,
    [COMPONENT.InputDatePicker]: Calendar,
    [COMPONENT.TimePicker]: Clock,
    [COMPONENT.Password]: Eye,
    [COMPONENT.ColorPicker]: Palette,
    [COMPONENT.Textarea]: FileText,
    [COMPONENT.Phone]: Phone,
    [COMPONENT.FileUpload]: Upload,
    [COMPONENT.Select]: List,
    [COMPONENT.Combobox]: List,
    [COMPONENT.Checkbox]: CheckSquare,
    [COMPONENT.Radio]: Radio,
    [COMPONENT.Switch]: ToggleLeft,
    [COMPONENT.RangeSlider]: Sliders,
    [COMPONENT.Link]: Link2,
    [COMPONENT.Button]: ButtonIcon,
    [COMPONENT.Text]: Type,
    [COMPONENT.Image]: Image,
    [COMPONENT.RichTextEditor]: Edit3,
    [COMPONENT.InputUrl]: Link,
    [COMPONENT.Table]: Table,
    [COMPONENT.Chart]: BarChart2,
    [COMPONENT.Maps]: Map,
    [COMPONENT.Carousel]: Play,
    [COMPONENT.Fingerprint]: Fingerprint,
    [COMPONENT.DatePickerRange]: Calendar,

    [COMPONENT.Panel]: Layout,
    [COMPONENT.Card]: CreditCard,
    [COMPONENT.Tabs]: Tabs,
    [COMPONENT.List]: ListIcon,
    [COMPONENT.iFrame]: Frame,
    [COMPONENT.InfoPanel]: Info,
    [COMPONENT.Calendar]: CalendarIcon,
    [COMPONENT.Alerts]: Bell,
    [COMPONENT.Badge]: Badge,
    [COMPONENT.Ratings]: Star,
    [COMPONENT.EmbedVideo]: Video,
    [COMPONENT.Progress]: Activity,
    // Chaves que não existem em COMPONENT permanecem iguais

    [COMPONENT.Form]: Form,
    [COMPONENT.Container]: Square,
    [COMPONENT.Grid]: Grid,
    [COMPONENT.Flex]: MoveRight,
    [COMPONENT.Columns]: Columns2,
    [COMPONENT.Column]: Columns2,
    [COMPONENT.Headline]: Heading1,
    [COMPONENT.Dropdown]: Ellipsis,
    [COMPONENT.Icon]: Heart,

    [COMPONENT.Piechart]: PieChart,
    [COMPONENT.Areachart]: AreaChart,
    [COMPONENT.Linechart]: LineChart,
    [COMPONENT.HorizontalBarchart]: ChartBarBig,
    [COMPONENT.VerticalBarchart]: ChartColumnBig,
    [COMPONENT.RadialBarchart]: Gauge,
    [COMPONENT.Radarchart]: RadarIcon,

    [COMPONENT.Chat]: MessageCircle,
    [COMPONENT.Search]: Search,
    [COMPONENT.StatsCard]: TrendingUp,
    [COMPONENT.Separator]: SeparatorHorizontal,
    [COMPONENT.ModalDialog]: CheckCircle,
    [COMPONENT.AlertDialog]: Info,
    [COMPONENT.Aspect]: Ratio,
    [COMPONENT.MenuNavigation]: Menu,
    [COMPONENT.Alert]: Dot,

    [COMPONENT.PageHeader]: Heading,
    [COMPONENT.Fragment]: Code,
    [COMPONENT.Paragraph]: WrapText,
    [COMPONENT.TextList]: WrapText,
    [COMPONENT.RepetitiveList]: LayoutList,
    [COMPONENT.FormList]: LayoutList,
    [COMPONENT.InfoCard]: CreditCard,
    [COMPONENT.PdfViewer]: FileText,
    [COMPONENT.StatusBanner]: Bell,

    [COMPONENT.Span]: TextIcon,
    [COMPONENT.Section]: RectangleHorizontal,

    [COMPONENT.Accordion]: AlignLeft,
    [COMPONENT.TreeView]: GitMerge,

    [COMPONENT.Notifications]: BellIcon,

    [COMPONENT.Stack]: Table2,

    [COMPONENT.TableDateFilter]: CalendarIcon,
    [COMPONENT.TableTextFilter]: FormInput,
    [COMPONENT.TableNumberFilter]: Sliders,
    [COMPONENT.TableCheckboxFilter]: CheckSquare,
    [COMPONENT.TableSelectFilter]: List,
    [COMPONENT.TableActionListCell]: ButtonIcon,
    [COMPONENT.TableAmountCell]: DollarSign,
    [COMPONENT.TableCheckboxCell]: CheckSquare,
    [COMPONENT.TableDateCell]: CalendarIcon,
    [COMPONENT.TableTextCell]: FormInput,
    [COMPONENT.TableExpanderCell]: ChevronDown,
    [COMPONENT.TableBadgeCell]: Badge,
} as const;

export const COMPONENT_MAP: Record<string, any> = {
    [COMPONENT.ColorPicker]: IGRPInputColor,
    [COMPONENT.Date]: IGRPDatePicker,
    [COMPONENT.DatePicker]: IGRPDatePicker,
    [COMPONENT.FileUpload]: IGRPInputFile,
    [COMPONENT.Number]: IGRPInputNumber,
    [COMPONENT.Password]: IGRPInputPassword,
    [COMPONENT.TimePicker]: IGRPInputTime,
    [COMPONENT.Phone]: IGRPInputPhone,
    [COMPONENT.Input]: IGRPInputText,
    [COMPONENT.InputText]: IGRPInputText,
    [COMPONENT.Textarea]: IGRPTextarea,
    [COMPONENT.Link]: IGRPInputUrl,
    [COMPONENT.AddOn]: IGRPInputAddOn,
    [COMPONENT.Select]: IGRPSelect,
    [COMPONENT.Combobox]: IGRPCombobox,
    [COMPONENT.Button]: IGRPButton,
    [COMPONENT.Label]: IGRPLabel,
    [COMPONENT.Checkbox]: IGRPCheckbox,
    [COMPONENT.Radio]: IGRPRadioGroup,
    [COMPONENT.Icon]: IGRPIcon,
    [COMPONENT.Headline]: IGRPHeadline,
    [COMPONENT.Text]: IGRPText,
    [COMPONENT.Switch]: IGRPSwitch,
    [COMPONENT.Search]: IGRPInputSearch,
    [COMPONENT.DatePickerRange]: IGRPDatePickerRange,

    [COMPONENT.Piechart]: IGRPPieChart,
    [COMPONENT.Areachart]: IGRPAreaChart,
    [COMPONENT.Linechart]: IGRPLineChart,
    [COMPONENT.HorizontalBarchart]: IGRPHorizontalBarChart,
    [COMPONENT.VerticalBarchart]: IGRPVerticalBarChart,
    [COMPONENT.Radarchart]: IGRPRadarChart,
    [COMPONENT.RadialBarchart]: IGRPRadialBarChart,

    [COMPONENT.Badge]: IGRPBadge,
    [COMPONENT.PdfViewer]: IGRPPdfViewer,

    [COMPONENT.TableInputFilter]: IGRPDataTableFilterInput,
    [COMPONENT.TableMinMaxFilter]: IGRPDataTableFilterMinMax,
    [COMPONENT.TableFilterDate]: IGRPDataTableFilterDate,
    [COMPONENT.TableSelectFilter]: IGRPDataTableFilterSelect,
    [COMPONENT.TableFacetedFilter]: IGRPDataTableFilterFaceted,
    [COMPONENT.TableFilterDropdown]: IGRPDataTableFilterDropdown,
    [COMPONENT.StatsCard]: IGRPStatsCard,
    [COMPONENT.Separator]: IGRPSeparator,
    [COMPONENT.AlertDialog]: IGRPAlertDialog,
    [COMPONENT.StatusBanner]: IGRPStatusBanner,

    [COMPONENT.Table]: IGRPStudioTable,
    [COMPONENT.Section]: IGRPStudioSection,
    [COMPONENT.Columns]: IGRPStudioColumns,
    [COMPONENT.Column]: IGRPStudioColumn,
    [COMPONENT.PageContent]: IGRPStudioPage,
    [COMPONENT.PageHeader]: IGRPStudioPageHeader,
    [COMPONENT.Form]: IGRPStudioForm,
    [COMPONENT.Container]: IGRPStudioContainer,
    [COMPONENT.Fragment]: IGRPStudioFragment,
    [COMPONENT.Card]: IGRPStudioCard,
    [COMPONENT.Flex]: IGRPStudioFlex,
    [COMPONENT.Grid]: IGRPStudioGrid,
    [COMPONENT.Tabs]: IGRPStudioTabs,
    [COMPONENT.Paragraph]: IGRPStudioParagraph,
    [COMPONENT.RepetitiveList]: IGRPStudioRepetitive,
    [COMPONENT.FormList]: IGRPStudioFormList,
    [COMPONENT.MenuNavigation]: IGRPStudioMenuNavigation,
    [COMPONENT.InfoCard]: IGRPStudioInfoCard,
    [COMPONENT.Alert]: IGRPStudioAlert,
    [COMPONENT.TextList]: IGRPStudioTextList,

    [COMPONENT.ModalDialog]: IGRPStudioModalDialog,
    [COMPONENT.ModalDialogTigger]: IGRPStudioDialogTrigger,
    [COMPONENT.ModalDialogTitle]: IGRPSTudioDialogTitle,
    [COMPONENT.ModalDialogHeader]: IGRPSTudioDialogHeader,
    [COMPONENT.ModalDialogDescription]: IGRPStudioDialogDescription,
    [COMPONENT.ModalDialogFooter]: IGRPSTudioDialogFooter
};
