// engines/DotNetEngine.ts
import {
    addController,
    addDTO,
    addEnum,
    addGraphQLSchema,
    addModel,
    addModule,
    addPermission,
    addResponse,
    deleteElement,
    engineTypes as dotnetEngineTypes,
    loadEngineConfiguration,
    newApi,
    serializeElement as createElement,
    setEngineConfiguration
} from '@igrp/dotnet-engine'
import type {
    BaseApiConfig,
    ControllerConfig,
    DeleteConfig,
    DTOConfig,
    EnumConfig,
    GraphQLSchemaConfig,
    ModelConfig,
    ModuleConfig,
    PermissionConfig,
    ResponseConfig
} from '@igrp/dotnet-engine/types'
import { app } from 'electron'
import { ensureDirectoryExists } from '../helpers'
import type { BaseEngine } from '../interfaces'
import type { DotNetConfigData, ProjectData } from '../types'

/**
 * IGRP Core library version pinned for `.NET` projects generated by Studio.
 * Sent as `BaseApiConfig.igrpCoreVersion`; the engine persists it to the
 * project's `.igrpstudio/baseApi.json` (Studio metadata). The IGRP Core
 * runtime itself is emitted as inline C# (e.g. `IgrpCoreServiceCollectionExtensions.cs`),
 * not pulled as a NuGet PackageReference — so this value records the
 * template/runtime contract rather than driving the generated `.csproj`.
 *
 * Update when bumping `@igrp/dotnet-engine` to a release whose templates
 * expect a newer IGRP Core. Kept inline here rather than in a shared
 * constants file because no other Studio call-site uses it.
 */
const IGRP_CORE_VERSION = '0.0.1-alpha.24'

/**
 * Derive a schema-valid `apiName` from the artifact / project name.
 *
 * `BaseApiConfig.apiName` is constrained by NAME_VALIDATION_PATTERN
 * (`^[A-Za-z][A-Za-z0-9_]*$`) — must start with a letter and contain only
 * alphanumerics or underscores. Studio's form collects an `artifact` such as
 * `"sample-api"` and an optional `name` like `"Sample API"`; neither passes
 * the pattern directly, so this strips disallowed characters and prefers the
 * project name when it yields a valid prefix.
 */
const deriveApiName = (artifact: string, projectName?: string): string => {
    const candidates = [projectName, artifact]
    for (const candidate of candidates) {
        if (!candidate) continue
        const cleaned = candidate.replace(/[^A-Za-z0-9_]/g, '')
        if (cleaned && /^[A-Za-z]/.test(cleaned)) return cleaned
    }
    throw new Error(
        `Cannot derive apiName from artifact "${artifact}". The artifact must contain at least one letter at the start.`
    )
}

/**
 * Idempotently switches `@igrp/dotnet-engine` to its production template
 * paths (`dist/templates/`) so the bundled artifact works the same way the
 * source tree does in-repo. Called from `registry()` on app startup AND at
 * the top of every operation so the smoke test (which doesn't go through
 * Studio's startup) still gets correct paths.
 *
 * Without this, `getPaths()` defaults to `../../public/templates`, which
 * doesn't exist under `node_modules/@igrp/dotnet-engine/dist/` because the
 * engine's `package.json` ships only `/dist`.
 */
const ensureProductionMode = (): void => {
    setEngineConfiguration({ environment: 'production' })
    loadEngineConfiguration()
}

export class DotNetEngine implements BaseEngine {
    async registry(): Promise<void> {
        ensureProductionMode()
    }

    async createProject(project: ProjectData, basePath: string): Promise<void> {
        ensureProductionMode()

        const config = project.config as DotNetConfigData

        const baseConfig: BaseApiConfig = {
            type: 'dotnet',
            apiName: deriveApiName(config.artifact, config.name),
            artifact: config.artifact,
            database: config.database,
            description: config.description,
            package: config.package,
            projectStructureStyle: config.projectStructureStyle,
            // Deliberately omit the human-readable `name` field: the engine
            // validates `context.baseConfig.name` as a C# identifier (no
            // spaces) and `apiName` already plays that role. Studio's
            // `DotNetConfigData.name` is a user-typed display string and may
            // contain spaces; passing it through breaks template rendering.
            enableObservability: !!config.enableObservability,
            enableEntityRevision: !!config.enableEntityRevision,
            igrpCoreVersion: IGRP_CORE_VERSION,
            // iGRP workspace identity + Studio manifest version (Spring parity —
            // see SpringEngine.createProject). `workspaceSlug`, when present,
            // additionally triggers the engine's workspace deployment files
            // (`igrp-compose-<name>.yaml` + `.igrp.<name>.env`) and CI
            // `REGISTRY_PROJECT`; `authMode` selects the identity provider (the
            // engine defaults to keycloak when omitted). All are round-trip-only
            // for the engine and are omitted from baseApi.json when undefined.
            workspaceId: project.workspaceId,
            workspaceSlug: config.workspaceSlug,
            version: app.getVersion(),
            authMode: config.authMode
        }

        await ensureDirectoryExists(basePath)
        await newApi(baseConfig, basePath)
    }

    async createModule(config: ModuleConfig, basePath: string): Promise<void> {
        await addModule(config, basePath)
    }

    async createModel(config: ModelConfig, basePath: string): Promise<void> {
        await addModel(config, basePath)
    }

    async createDto(config: DTOConfig, basePath: string): Promise<void> {
        await addDTO(config, basePath)
    }

    async createEnum(config: EnumConfig, basePath: string): Promise<void> {
        await addEnum(config, basePath)
    }

    async createController(config: ControllerConfig, basePath: string): Promise<void> {
        await addController(config, basePath)
    }

    async createGraphqlSchema(config: GraphQLSchemaConfig, basePath: string): Promise<void> {
        await addGraphQLSchema(config, basePath)
    }

    async createResponse(config: ResponseConfig, basePath: string): Promise<void> {
        await addResponse(config, basePath)
    }

    async createPermission(config: PermissionConfig, basePath: string): Promise<void> {
        await addPermission(config, basePath)
    }

    async delete(config: DeleteConfig, basePath: string): Promise<void> {
        await deleteElement(config, basePath)
    }

    async duplicate(config: any, basePath: string): Promise<void> {
        // Mirrors SpringEngine.duplicate: deep-clone, rename, re-emit via the
        // type-specific operation. Kept here so Studio's IPC contract behaves
        // the same regardless of which backend framework the project uses.
        const { name, type, module, content } = config
        const duplicateName = `${name}Copy`
        const duplicateContent = JSON.parse(JSON.stringify(content))
        duplicateContent.name = duplicateName
        duplicateContent.id = `${duplicateContent.id}_copy`

        switch (type) {
            case 'model':
                // A duplicated entity must not share its table — or any
                // DB-scoped constraint/index name — with the original. EF Core
                // refuses to build a model where two entity types map to the
                // same table without a linking relationship ("Cannot use table
                // 'departments' for entity type 'DepartmentCopy' since it is
                // being used for entity type 'Department'…"), and Postgres
                // rejects duplicate constraint/index names at migration time.
                // Suffix them so the copy is an independent, migratable entity.
                if (duplicateContent.tableName) {
                    duplicateContent.tableName = `${duplicateContent.tableName}_copy`
                }
                if (Array.isArray(duplicateContent.uniqueConstraints)) {
                    duplicateContent.uniqueConstraints = duplicateContent.uniqueConstraints.map(
                        (uc: any) => (uc?.name ? { ...uc, name: `${uc.name}_copy` } : uc)
                    )
                }
                if (Array.isArray(duplicateContent.indexes)) {
                    duplicateContent.indexes = duplicateContent.indexes.map((ix: any) =>
                        ix?.name ? { ...ix, name: `${ix.name}_copy` } : ix
                    )
                }
                await addModel({ ...duplicateContent, module }, basePath)
                break
            case 'dto':
                await addDTO({ ...duplicateContent, module }, basePath)
                break
            case 'controller':
                await addController({ ...duplicateContent, module }, basePath)
                break
            case 'enum':
                await addEnum({ ...duplicateContent, module }, basePath)
                break
            case 'response':
                await addResponse({ ...duplicateContent, module }, basePath)
                break
            default:
                throw new Error(`Unsupported type for duplication: ${type}`)
        }
    }

    async serializeElement(data: any, basePath: string): Promise<void> {
        await createElement(data, basePath)
    }

    async engineTypes(module: string, basePath: string): Promise<any> {
        return await dotnetEngineTypes(module, basePath)
    }
}
