/**
 * Pure converter: canonical Entity[] → CREATE TABLE DDL for PostgreSQL or
 * MySQL. Migrations / Liquibase / runtime schema mutation are out of scope —
 * this just emits a self-contained script you can paste into a SQL client.
 *
 * `advancedType` overrides win when set (escape hatch for types outside the
 * canonical set).
 */
import type { Entity, Field, FieldType } from '../spec-data-service'

export type DdlDialect = 'postgresql' | 'mysql'

const PG_TYPE_MAP: Record<FieldType, string> = {
    string: 'TEXT',
    int: 'INTEGER',
    decimal: 'NUMERIC',
    boolean: 'BOOLEAN',
    date: 'DATE',
    datetime: 'TIMESTAMP',
    json: 'JSONB',
    enum: 'TEXT',          // emitted with a CHECK when enumValues set
    reference: 'TEXT'      // resolved per-target below
}

const MYSQL_TYPE_MAP: Record<FieldType, string> = {
    string: 'VARCHAR(255)',
    int: 'INT',
    decimal: 'DECIMAL(20,6)',
    boolean: 'TINYINT(1)',
    date: 'DATE',
    datetime: 'DATETIME',
    json: 'JSON',
    enum: 'VARCHAR(64)',   // emitted as ENUM(...) when enumValues set
    reference: 'VARCHAR(255)'
}

export function entitiesToDdl(entities: Entity[], dialect: DdlDialect): string {
    const idToName = new Map(entities.map((e) => [e.id, e.name]))
    const idToPkName = new Map(
        entities.map((e) => {
            const pk = e.fields.find((f) => f.primaryKey)
            return [e.id, pk?.name ?? 'id']
        })
    )
    const q = dialect === 'mysql' ? mysqlIdent : pgIdent

    const tableBlocks: string[] = []
    const fkBlocks: string[] = []
    const indexBlocks: string[] = []

    for (const entity of entities) {
        const tableName = q(toSnake(entity.name))
        const lines: string[] = []
        const pkCols: string[] = []

        for (const f of entity.fields) {
            lines.push(`    ${q(toSnake(f.name))} ${columnDeclaration(f, dialect, idToName)}`)
            if (f.primaryKey) pkCols.push(q(toSnake(f.name)))
        }

        if (pkCols.length > 0) {
            lines.push(`    PRIMARY KEY (${pkCols.join(', ')})`)
        }

        let block = `CREATE TABLE ${tableName} (\n${lines.join(',\n')}\n);`
        if (entity.description) {
            block = `-- ${entity.description}\n${block}`
        }
        tableBlocks.push(block)

        // Foreign keys (split into ALTER TABLE so cyclical refs don't break).
        for (const f of entity.fields) {
            if (f.type !== 'reference' || !f.referenceEntityId) continue
            const targetName = idToName.get(f.referenceEntityId)
            if (!targetName) continue
            const targetTable = q(toSnake(targetName))
            const targetPk = q(toSnake(idToPkName.get(f.referenceEntityId) ?? 'id'))
            fkBlocks.push(
                `ALTER TABLE ${tableName} ADD CONSTRAINT ${q(
                    `fk_${toSnake(entity.name)}_${toSnake(f.name)}`
                )} FOREIGN KEY (${q(toSnake(f.name))}) REFERENCES ${targetTable}(${targetPk});`
            )
        }

        // Indexes (skip pk + reference targets which are FK-indexed by default).
        for (const f of entity.fields) {
            if (!f.indexed || f.primaryKey) continue
            indexBlocks.push(
                `CREATE INDEX ${q(`idx_${toSnake(entity.name)}_${toSnake(f.name)}`)} ON ${tableName} (${q(toSnake(f.name))});`
            )
        }
    }

    const sections: string[] = []
    sections.push(
        `-- Generated by IGRP Studio · Data Models · dialect=${dialect}\n-- ${new Date().toISOString()}\n`
    )
    if (tableBlocks.length) sections.push(tableBlocks.join('\n\n'))
    if (fkBlocks.length) sections.push('-- Foreign keys\n' + fkBlocks.join('\n'))
    if (indexBlocks.length) sections.push('-- Indexes\n' + indexBlocks.join('\n'))
    return sections.join('\n\n') + '\n'
}

function columnDeclaration(
    field: Field,
    dialect: DdlDialect,
    idToName: Map<string, string>
): string {
    const parts: string[] = []
    parts.push(resolveColumnType(field, dialect, idToName))
    if (field.nullable === false || field.primaryKey) parts.push('NOT NULL')
    if (field.unique && !field.primaryKey) parts.push('UNIQUE')
    if (field.defaultValue != null && !field.primaryKey) {
        parts.push(`DEFAULT ${formatDefault(field.defaultValue, field.type, dialect)}`)
    }
    if (field.description) parts.push(`-- ${sanitizeComment(field.description)}`)
    return parts.join(' ')
}

function resolveColumnType(
    field: Field,
    dialect: DdlDialect,
    idToName: Map<string, string>
): string {
    if (field.advancedType) return field.advancedType
    if (field.type === 'enum' && field.enumValues && field.enumValues.length > 0) {
        if (dialect === 'mysql') {
            return `ENUM(${field.enumValues.map(quoteString).join(', ')})`
        }
        // Postgres: TEXT + CHECK constraint inline.
        return `TEXT CHECK (${pgIdent(toSnake(field.name))} IN (${field.enumValues.map(quoteString).join(', ')}))`
    }
    if (field.type === 'reference' && field.referenceEntityId) {
        // Match the target's primary key type — assume INTEGER if pk; fallback TEXT.
        const targetName = idToName.get(field.referenceEntityId)
        if (targetName) {
            // Without access to target's pk type here, default to INTEGER (most common).
            // Users can refine via advancedType if needed.
            return dialect === 'mysql' ? 'INT' : 'INTEGER'
        }
    }
    return dialect === 'mysql' ? MYSQL_TYPE_MAP[field.type] : PG_TYPE_MAP[field.type]
}

function formatDefault(
    value: string | number | boolean | null,
    type: FieldType,
    dialect: DdlDialect
): string {
    if (value === null) return 'NULL'
    if (type === 'boolean') {
        const truthy = value === true || value === 'true' || value === 1 || value === '1'
        if (dialect === 'mysql') return truthy ? '1' : '0'
        return truthy ? 'TRUE' : 'FALSE'
    }
    if (type === 'int' || type === 'decimal') {
        return Number.isFinite(Number(value)) ? String(value) : 'NULL'
    }
    return quoteString(String(value))
}

function quoteString(value: string): string {
    return `'${value.replace(/'/g, "''")}'`
}

function pgIdent(name: string): string {
    return `"${name.replace(/"/g, '""')}"`
}

function mysqlIdent(name: string): string {
    return `\`${name.replace(/`/g, '``')}\``
}

function toSnake(name: string): string {
    return name
        .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
        .replace(/[\s-]+/g, '_')
        .toLowerCase()
}

function sanitizeComment(text: string): string {
    return text.replace(/\r?\n/g, ' ').slice(0, 200)
}
