apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://demoteste-prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://demoteste-loki:3100
    editable: true
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: '(?:trace_id|traceId|traceID|trace)=([a-fA-F0-9]{16,32})'
          datasourceUid: tempo
          url: '${__value.raw}'

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://demoteste-tempo:3200
    editable: true
    jsonData:
      httpMethod: GET
      nodeGraph:
        enabled: true
      search:
        hide: false
      serviceMap:
        datasourceUid: prometheus
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: -1h
        spanEndTimeShift: 1h
        filterByTraceID: true
        filterBySpanID: false
        tags:
          - key: service.name
            value: service
      tracesToMetrics:
        datasourceUid: prometheus
        spanStartTimeShift: -1h
        spanEndTimeShift: 1h
        tags:
          - key: service.name
            value: service
        queries:
          - name: Request rate
            query: sum(rate(traces_spanmetrics_calls_total{$__tags}[5m]))
          - name: Request latency
            query: histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{$__tags}[5m])) by (le))
