/**
 * Preview-only mock-data seeding for the Prototype Builder.
 *
 * Architectural separation (M7):
 *   - `.igrpstudio/prototype/page.json`          ← canonical manifest, dev handoff
 *   - `.igrpstudio/prototype/preview/<name>.mock.json` ← Studio-managed mock
 *   - `prototype/src/app/(igrp)/(generated)/<route>/_preview.ts` ← sibling
 *     of `page.tsx`, imports the mock JSON. Clearly marked as preview-only.
 *   - `prototype/src/app/(igrp)/(generated)/<route>/page.tsx`     ← engine-
 *     generated; the seeder rewrites it once to add a
 *     `/* PREVIEW BEGIN/END *​/` block that calls `setTableData(previewSeed.…)`
 *     from `useEffect`. The block is fence-delimited so a future
 *     `export --production` strips it deterministically.
 *
 * Why a second LLM turn (and not template-inflate from `types[]`):
 *   - The LLM picks realistic values keyed off the spec terminology
 *     (`"Acme Corp"`, `"INV-001"`) — template-inflate would produce
 *     `"string_1"`, `"string_2"`, useless for visual review.
 *   - Same provider/model as the manifest turn; cost is small (~3-6 rows).
 *
 * Failure modes are non-fatal: every step degrades to "skip seeding,
 * preview shows empty table" rather than rolling back the manifest gen.
 */
import { promises as fsp } from 'node:fs'
import { dirname, join, relative as pathRelative } from 'node:path'
import { llmRouter } from '../llm/llm-router'
import type { LLMMessage } from '../llm/types'

const PREVIEW_BEGIN = '/* PREVIEW BEGIN — auto-generated by iGRP Studio; strip on production export */'
const PREVIEW_END = '/* PREVIEW END */'

export interface SeedInput {
    basePath: string
    /** Manifest the engine just consumed — we extract `types[]` + `states[]`. */
    manifest: { pageName: string; path: string; types?: unknown[]; states?: unknown[] }
    /** Absolute path to the `page.tsx` the engine wrote. */
    pageTsxPath: string
    providerId: string
    model: string
    signal?: AbortSignal
}

export interface SeedResult {
    ok: boolean
    /** Path to `<pageName>.mock.json` (relative to project for log clarity). */
    mockJsonPath?: string
    /** Path to `_preview.ts` (relative to project). */
    previewTsPath?: string
    /** Number of rows generated per state. */
    rowCount?: number
    /** Non-fatal reason — caller still considers turn successful. */
    skippedReason?: string
    error?: string
}

interface TypeDef {
    name: string
    fields: Array<{ name: string; type: string }>
}

interface StateDef {
    name: string
    type: string
    isArray?: boolean
}

/**
 * Drive the seeding step end-to-end. Idempotent — if the markers already
 * exist in `page.tsx` we replace them rather than stacking blocks.
 */
export async function seedPreviewMockData(input: SeedInput): Promise<SeedResult> {
    const { basePath, manifest, pageTsxPath } = input

    // 1. Extract the array-states that need seeding. Only `isArray: true`
    //    states with a non-primitive `type` (matching a `types[].name`)
    //    qualify — that's the table-bound case. Scalar counters
    //    (`totalCount: number`) are derived in the preview block, not
    //    seeded from the LLM directly.
    const types = normaliseTypes(manifest.types)
    const states = normaliseStates(manifest.states)
    const seedable = states.filter(
        (s) => s.isArray && types.some((t) => t.name === s.type)
    )
    if (seedable.length === 0) {
        return {
            ok: true,
            skippedReason:
                'Manifest has no array-state bound to a typed row shape — nothing to seed.'
        }
    }

    // 2. Read the engine-generated `page.tsx` and discover the EXACT
    //    column ids the table renders (e.g. `cellNumber`, `cellStatus`).
    //    These differ from `types[].fields[].name` because the engine
    //    applies its own naming convention when synthesising columns
    //    from a `dataType` reference. Seeding against `field.name`
    //    produces mocks the table can't read (`row.original.cellStatus`
    //    is undefined when the mock has `status`). Reading the actual
    //    generated code is the only way to stay in sync without
    //    duplicating the engine's transformation rules.
    let pageTsxContent: string
    try {
        pageTsxContent = await fsp.readFile(pageTsxPath, 'utf-8')
    } catch (err) {
        return {
            ok: false,
            error: `Could not read generated page.tsx: ${err instanceof Error ? err.message : String(err)}`
        }
    }
    const renderedTables = extractTableColumnsFromPageTsx(pageTsxContent)

    // 3. Ask the LLM for 3–6 rows per seedable state, using the actual
    //    column ids as the JSON keys. Fall back to the type fields when
    //    we couldn't match the state to a rendered table (rare — only
    //    if the engine changed the binding name unexpectedly).
    let mock: Record<string, unknown[]>
    try {
        mock = await generateMockRows({
            providerId: input.providerId,
            model: input.model,
            signal: input.signal,
            pageName: manifest.pageName,
            requests: seedable.map((s) => {
                const matched = renderedTables.find(
                    (t) => t.boundStateName === s.name
                )
                const fields = types.find((t) => t.name === s.type)?.fields ?? []
                return {
                    stateName: s.name,
                    typeName: s.type,
                    // Prefer columns from the actual rendered TSX — these
                    // are what `row.getValue(...)` / `row.original.<key>`
                    // will look for. Field-name fallback covers the case
                    // where the regex couldn't find the table (defensive).
                    columns:
                        matched && matched.columns.length > 0
                            ? matched.columns
                            : fields.map((f) => f.name),
                    // Keep the field type hints so the LLM emits the
                    // right primitives (numbers as numbers, dates as ISO
                    // strings). We don't have a 1:1 column→field map, so
                    // we pass them as orientation rather than strict
                    // pairing.
                    fieldHints: fields
                }
            })
        })
    } catch (err) {
        return {
            ok: false,
            error: `Mock generation LLM call failed: ${err instanceof Error ? err.message : String(err)}`
        }
    }

    // 3. Write `.igrpstudio/prototype/preview/<pageName>.mock.json`.
    const mockJsonAbs = join(
        basePath,
        '.igrpstudio',
        'prototype',
        'preview',
        `${manifest.pageName}.mock.json`
    )
    try {
        await fsp.mkdir(dirname(mockJsonAbs), { recursive: true })
        await fsp.writeFile(mockJsonAbs, JSON.stringify(mock, null, 2) + '\n', 'utf-8')
    } catch (err) {
        return {
            ok: false,
            error: `Could not write mock JSON: ${err instanceof Error ? err.message : String(err)}`
        }
    }

    // 4. Write `_preview.ts` sibling of `page.tsx`. Its sole job is to
    //    re-export the mock JSON through a typed `previewSeed` const, so
    //    the injected preview block can `import { previewSeed } from
    //    './_preview'` without spelling out a deep relative path on every
    //    page. Computed at runtime so we don't have to know the depth
    //    upfront.
    const pageDir = dirname(pageTsxPath)
    const previewTsAbs = join(pageDir, '_preview.ts')
    const relMockJson = computeRelativeImport(previewTsAbs, mockJsonAbs)
    const previewTsContent =
        '// AUTO-GENERATED FOR PREVIEW — DO NOT COMMIT TO PRODUCTION\n' +
        '// Sibling of page.tsx. Deleted on `igrp prototype export --production`.\n' +
        `import mock from '${relMockJson}';\n` +
        'export const previewSeed = mock;\n'
    try {
        await fsp.writeFile(previewTsAbs, previewTsContent, 'utf-8')
    } catch (err) {
        return {
            ok: false,
            error: `Could not write _preview.ts: ${err instanceof Error ? err.message : String(err)}`
        }
    }

    // 5. Inject the seeding block into `page.tsx` between PREVIEW
    //    BEGIN/END markers. Idempotent: if markers already exist (turn 2+
    //    on the same page) we replace the block. `pageTsxContent` was
    //    read in step 2 — reuse it.
    try {
        const patched = patchPageTsx(pageTsxContent, seedable, manifest.pageName)
        if (patched !== pageTsxContent) {
            await fsp.writeFile(pageTsxPath, patched, 'utf-8')
        }
    } catch (err) {
        return {
            ok: false,
            error: `Could not patch page.tsx: ${err instanceof Error ? err.message : String(err)}`
        }
    }

    const rowCount = Math.max(...Object.values(mock).map((v) => v.length), 0)
    return {
        ok: true,
        mockJsonPath: mockJsonAbs,
        previewTsPath: previewTsAbs,
        rowCount
    }
}

// ─── manifest normalisation ─────────────────────────────────────────────

function normaliseTypes(raw: unknown): TypeDef[] {
    if (!Array.isArray(raw)) return []
    const out: TypeDef[] = []
    for (const entry of raw) {
        if (!entry || typeof entry !== 'object') continue
        const o = entry as Record<string, unknown>
        if (typeof o.name !== 'string') continue
        const fields: TypeDef['fields'] = []
        if (Array.isArray(o.fields)) {
            for (const f of o.fields) {
                if (!f || typeof f !== 'object') continue
                const fo = f as Record<string, unknown>
                if (typeof fo.name === 'string' && typeof fo.type === 'string') {
                    fields.push({ name: fo.name, type: fo.type })
                }
            }
        }
        out.push({ name: o.name, fields })
    }
    return out
}

function normaliseStates(raw: unknown): StateDef[] {
    if (!Array.isArray(raw)) return []
    const out: StateDef[] = []
    for (const entry of raw) {
        if (!entry || typeof entry !== 'object') continue
        const o = entry as Record<string, unknown>
        if (typeof o.name !== 'string' || typeof o.type !== 'string') continue
        out.push({
            name: o.name,
            type: o.type,
            isArray: o.isArray === true
        })
    }
    return out
}

// ─── page.tsx introspection ─────────────────────────────────────────────
//
// The engine applies its own naming convention when generating data-table
// columns from a `dataType` reference (e.g. it prefixes `cell` to a
// camelCased field name). Reading the rendered TSX gives us the exact
// keys `row.getValue(...)` / `row.original.<key>` will look for —
// duplicating the engine's rule on the Studio side would drift.
//
// Regex-based extraction is good enough here: the engine generates a
// very predictable shape (`<IGRPDataTable ... columns={[{ id: '…' }, …]}
// data={tableName} />`), and the TSX is auto-generated (no comments or
// formatting variants to defend against).

export interface RenderedTable {
    /** The state name bound via `data={…}`. `null` when not found. */
    boundStateName: string | null
    /** Ordered column ids — the JSON keys the UI reads from each row. */
    columns: string[]
}

export function extractTableColumnsFromPageTsx(content: string): RenderedTable[] {
    const tables: RenderedTable[] = []
    // Each `<IGRPDataTable …` opening, captured up to its first `/>` —
    // engine output is always self-closing for IGRPDataTable, so we
    // don't need to balance an explicit closing tag.
    const tableRe = /<IGRPDataTable\b[\s\S]*?\/>/g
    let m: RegExpExecArray | null
    while ((m = tableRe.exec(content))) {
        const block = m[0]
        const dataMatch = block.match(/\bdata=\{(\w+)\}/)
        const boundStateName = dataMatch ? dataMatch[1] : null
        // Column ids: `id: 'cellNumber'` inside the columns array. We
        // scan the WHOLE table block (not just the columns subrange)
        // because the regex anchor for the array is brittle, and the
        // engine doesn't emit `id:` strings outside columns in this
        // component.
        const cols: string[] = []
        const colRe = /\bid:\s*['"]([^'"]+)['"]/g
        let cm: RegExpExecArray | null
        while ((cm = colRe.exec(block))) {
            // Skip the table's own `id` prop (which appears as
            // `id={`tableInvoices`}` with backticks, not `id: '…'`).
            // We're matching the comma-form here so this is naturally
            // distinct.
            cols.push(cm[1])
        }
        tables.push({ boundStateName, columns: cols })
    }
    return tables
}

// ─── LLM call ───────────────────────────────────────────────────────────

interface MockRequest {
    stateName: string
    typeName: string
    /**
     * EXACT JSON keys the rendered table reads via `row.getValue(...)` /
     * `row.original.<key>`. Discovered by parsing the engine-generated
     * `page.tsx` — these are the only keys the UI will look at.
     */
    columns: string[]
    /**
     * Type hints from `types[].fields[]` — used to guide the LLM toward
     * the right primitives (number / date / boolean). NOT a strict
     * 1:1 mapping with columns; the LLM matches by name similarity
     * (`amount` → number, `issueDate` → date string).
     */
    fieldHints: Array<{ name: string; type: string }>
}

/**
 * Ask the LLM for `{ stateName: [row, row, …] }`. Single fenced JSON
 * block, no prose. We keep the prompt short and concrete — this isn't a
 * generation task, it's a name-the-rows task.
 */
async function generateMockRows(args: {
    providerId: string
    model: string
    signal?: AbortSignal
    pageName: string
    requests: MockRequest[]
}): Promise<Record<string, unknown[]>> {
    const requestsBlock = args.requests
        .map((r) => {
            const colsList = r.columns.map((c) => `  - \`${c}\``).join('\n')
            const hintsList =
                r.fieldHints.length > 0
                    ? '\n  Type hints (match by name similarity to the columns above): ' +
                      r.fieldHints.map((f) => `\`${f.name}\`=${f.type}`).join(', ')
                    : ''
            return (
                `- **${r.stateName}** (rows of type \`${r.typeName}\`):\n` +
                `  Required keys per row (use EXACTLY these JSON keys):\n` +
                colsList +
                hintsList
            )
        })
        .join('\n')

    const system = [
        'You are generating preview-only mock data for an iGRP Studio prototype.',
        'Reply with EXACTLY one fenced ```json``` block — an object keyed by',
        'state name. Each value is an array of 4–6 realistic rows matching the',
        'shape described below. No prose, no commentary outside the fence.',
        '',
        '## Rules',
        '- **Use the EXACT JSON keys listed for each state.** The keys come from',
        '  the rendered data-table component ids (e.g. `cellNumber`,',
        '  `cellStatus`); the UI only reads those keys. Do NOT rename them to',
        '  human-friendly or API-style alternatives.',
        '- Use realistic, domain-appropriate values that match the page name and',
        '  key semantics inferred by name (e.g. for an `invoices` page, customer',
        '  names like "Acme Corp", invoice numbers like "INV-001", amounts as',
        '  strings "1200.00").',
        '- Stay in ASCII (no accents) — IGRP page slug / engine constraints.',
        '- Every row needs an `id` field (string) even if the type does not',
        '  declare it — the data-table requires it for row keys. If `id` is',
        '  already in the column list, use that; otherwise add it.',
        '- Use the type hints to pick primitives correctly: `number` → real',
        '  numbers (NOT strings); `boolean` → real booleans; `date` → ISO',
        '  strings like "2026-01-15"; `string` → JSON strings; `object` →',
        '  nested objects. When in doubt, prefer strings.',
        '- Vary values across rows (don\'t repeat "Acme Corp" four times).',
        '- For status-like keys (anything containing `status`, `state`,',
        '  `estado`), spread values across the realistic enum visible in the',
        '  page context (e.g. paid/pending/overdue, active/inactive).'
    ].join('\n')

    const user = [
        `Page: \`${args.pageName}\``,
        '',
        '## States to seed',
        '',
        requestsBlock,
        '',
        'Return JSON matching:',
        '```',
        '{',
        ...args.requests.map((r) => `  "${r.stateName}": [ /* 4-6 rows */ ],`),
        '}',
        '```'
    ].join('\n')

    const messages: LLMMessage[] = [{ role: 'user', content: user }]
    let buffer = ''
    const stream = llmRouter.chat(args.providerId, messages, {
        model: args.model,
        systemPrompt: system,
        signal: args.signal
    })
    for await (const chunk of stream) {
        if (chunk.type === 'delta') buffer += chunk.content
        else if (chunk.type === 'error') {
            throw new Error(chunk.message)
        } else if (chunk.type === 'done') break
    }

    if (!buffer.trim()) throw new Error('Empty reply from mock generator.')

    // Extract fenced JSON (same heuristic as the manifest path).
    const fence = buffer.match(/```(?:json)?\s*([\s\S]*?)```/i)
    const raw = fence ? fence[1].trim() : buffer.trim()
    let parsed: unknown
    try {
        parsed = JSON.parse(raw)
    } catch (err) {
        throw new Error(
            `Mock JSON parse failed: ${err instanceof Error ? err.message : String(err)}`
        )
    }
    if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
        throw new Error('Mock reply root must be an object.')
    }
    const out: Record<string, unknown[]> = {}
    for (const [k, v] of Object.entries(parsed as Record<string, unknown>)) {
        if (Array.isArray(v)) out[k] = v
    }
    if (Object.keys(out).length === 0) throw new Error('Mock reply has no arrays.')
    return out
}

// ─── page.tsx patching ──────────────────────────────────────────────────

/**
 * Compute a JS-importable relative path from `fromFile` to `toFile`,
 * starting with `./` or `../` and stripping `.json` only when the
 * extension is `.ts`/`.tsx` (here we always import a JSON, so we keep
 * the `.json` suffix — Next.js + TypeScript both honour
 * `resolveJsonModule`).
 */
function computeRelativeImport(fromFile: string, toFile: string): string {
    const fromDir = dirname(fromFile)
    let rel = pathRelative(fromDir, toFile)
    // Normalise Windows separators for the source code we emit.
    rel = rel.replace(/\\/g, '/')
    if (!rel.startsWith('.')) rel = './' + rel
    return rel
}

/**
 * Inject (or replace) the seeding block in `page.tsx`. The block:
 *
 *   1. Adds an `import { previewSeed } from './_preview'` near the
 *      other imports (only when not already present).
 *   2. Adds `useEffect(() => { setStateX(previewSeed.stateX); ... }, [])`
 *      right after the first `const { igrpToast } = useIGRPToast();`
 *      (or the function-body opening `{` if that line is missing).
 *
 * Both edits live between `PREVIEW BEGIN` and `PREVIEW END` markers so
 * a production-export step can `sed` them out deterministically.
 */
function patchPageTsx(source: string, seedable: StateDef[], pageName: string): string {
    if (seedable.length === 0) return source

    // 1. Strip any existing preview region so re-runs replace cleanly.
    const stripped = source.replace(
        new RegExp(
            // The (?:[\\s\\S]*?) keeps the strip non-greedy across both the
            // import-region and the useEffect-region instances.
            escapeRegExp(PREVIEW_BEGIN) +
                '[\\s\\S]*?' +
                escapeRegExp(PREVIEW_END) +
                '\\n?',
            'g'
        ),
        ''
    )

    // 2. Add the import block right after the LAST import statement.
    //    Imports can span multiple lines (`import { A, B, } from '…';`),
    //    so we can't just find the last line starting with `import` —
    //    that would split a multi-line import in half. We walk the
    //    source tracking whether we're inside an import block and
    //    record the line index where the most recent one TERMINATED
    //    (the line containing the closing `;`).
    const importBlock =
        `${PREVIEW_BEGIN}\n` +
        `import { previewSeed } from './_preview';\n` +
        `${PREVIEW_END}\n`
    const lines = stripped.split('\n')
    let inImport = false
    let lastImportEndIdx = -1
    for (let i = 0; i < lines.length; i++) {
        const line = lines[i]
        if (!inImport && /^\s*import\s/.test(line)) {
            inImport = true
        }
        if (inImport) {
            // Statement terminator: any `;` outside a string. The engine
            // never emits semicolons inside import strings, so a plain
            // `;` test is enough for our generated files.
            if (/;\s*(?:\/\/.*)?\s*$/.test(line)) {
                lastImportEndIdx = i
                inImport = false
            }
        }
    }
    let withImport = stripped
    if (lastImportEndIdx >= 0) {
        lines.splice(lastImportEndIdx + 1, 0, '', importBlock.trimEnd())
        withImport = lines.join('\n')
    } else {
        // No imports at all — prepend the block (very unlikely for
        // engine-generated TSX).
        withImport = importBlock + stripped
    }

    // 3. Build the useEffect — one setStateX call per seedable state.
    //    The setState name is the standard React convention: `set` +
    //    state name with first letter uppercased. Indentation matches
    //    the engine's 2-space style inside the component body (2 for
    //    the block, 4 for the body of useEffect).
    const calls = seedable
        .map((s) => `    set${capitalise(s.name)}(previewSeed.${s.name} as any);`)
        .join('\n')
    const effectBlock =
        `  ${PREVIEW_BEGIN}\n` +
        `  // Preview seed for ${pageName} — strip when wiring real backend.\n` +
        `  // eslint-disable-next-line react-hooks/exhaustive-deps\n` +
        `  useEffect(() => {\n` +
        calls +
        `\n  }, []);\n` +
        `  ${PREVIEW_END}\n`

    // Anchor: the line right after `useIGRPToast();` inside the component
    // body. The engine consistently emits that destructure for every
    // page. Fall back to the first `return (` if the toast line is
    // missing (defensive).
    const toastAnchor = withImport.match(
        /(^[ \t]*const\s+\{\s*igrpToast\s*\}\s*=\s*useIGRPToast\(\);\s*\n)/m
    )
    if (toastAnchor && toastAnchor.index !== undefined) {
        const insertAt = toastAnchor.index + toastAnchor[0].length
        return withImport.slice(0, insertAt) + '\n' + effectBlock + withImport.slice(insertAt)
    }
    const returnAnchor = withImport.match(/(\n[ \t]*return\s*\()/m)
    if (returnAnchor && returnAnchor.index !== undefined) {
        return (
            withImport.slice(0, returnAnchor.index + 1) +
            effectBlock +
            withImport.slice(returnAnchor.index + 1)
        )
    }
    // Couldn't find an anchor — leave source untouched rather than
    // produce a broken file.
    return source
}

function capitalise(s: string): string {
    return s.length === 0 ? s : s[0].toUpperCase() + s.slice(1)
}

function escapeRegExp(s: string): string {
    return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

// Re-export so tests can target the patcher independently of LLM I/O.
export const _internals = {
    patchPageTsx,
    normaliseTypes,
    normaliseStates,
    extractTableColumnsFromPageTsx
}
