// This is a script to extract Lucide icons data from HTML and output as JSON
// Note: In a real environment, this would parse the actual HTML file

// Sample of the structure we're generating
// This represents the actual data that would be extracted from lucide.html
export const lucideIconsConfig = {
    "categories": [
      "Accessibility",
      "Account",
      "Arrows",
      "Buildings",
      "Business",
      "Charts",
      "Communication",
      "Connectivity",
      "Design",
      "Devices",
      "Ecommerce",
      "Editing",
      "Files",
      "Food & Beverage",
      "Gaming",
      "Health",
      "Logos",
      "Maps",
      "Media",
      "Medical",
      "Money",
      "Nature",
      "Objects",
      "Photography",
      "Security",
      "Shapes",
      "Shopping",
      "Social",
      "Sports",
      "Text",
      "Time",
      "Tools",
      "Transportation",
      "Travel",
      "Weather"
    ],
    "icons": [
      { "name": "accessibility", "category": "Accessibility" },
      { "name": "braille", "category": "Accessibility" },
      { "name": "ear", "category": "Accessibility" },
      { "name": "ear-off", "category": "Accessibility" },
      { "name": "eye", "category": "Accessibility" },
      { "name": "eye-off", "category": "Accessibility" },
      { "name": "hand-metal", "category": "Accessibility" },
      { "name": "hearing-aid", "category": "Accessibility" },
      { "name": "wheelchair", "category": "Accessibility" },
      
      { "name": "activity", "category": "Health" },
      { "name": "activity-square", "category": "Health" },
      { "name": "ambulance", "category": "Medical" },
      { "name": "angry", "category": "Account" },
      { "name": "aperture", "category": "Photography" },
      { "name": "apple", "category": "Food & Beverage" },
      { "name": "archive", "category": "Files" },
      { "name": "archive-restore", "category": "Files" },
      { "name": "armchair", "category": "Objects" },
      { "name": "arrow-big-down", "category": "Arrows" },
      { "name": "arrow-big-left", "category": "Arrows" },
      { "name": "arrow-big-right", "category": "Arrows" },
      { "name": "arrow-big-up", "category": "Arrows" },
      { "name": "arrow-down", "category": "Arrows" },
      { "name": "arrow-down-circle", "category": "Arrows" },
      { "name": "arrow-down-left", "category": "Arrows" },
      { "name": "arrow-down-right", "category": "Arrows" },
      { "name": "arrow-left", "category": "Arrows" },
      { "name": "arrow-left-circle", "category": "Arrows" },
      { "name": "arrow-right", "category": "Arrows" },
      { "name": "arrow-right-circle", "category": "Arrows" },
      { "name": "arrow-up", "category": "Arrows" },
      { "name": "arrow-up-circle", "category": "Arrows" },
      { "name": "arrow-up-down", "category": "Arrows" },
      { "name": "arrow-up-left", "category": "Arrows" },
      { "name": "arrow-up-right", "category": "Arrows" },
      
      { "name": "asterisk", "category": "Text" },
      { "name": "at-sign", "category": "Communication" },
      { "name": "atom", "category": "Science" },
      { "name": "award", "category": "Objects" },
      { "name": "axe", "category": "Tools" },
      { "name": "baby", "category": "Account" },
      { "name": "backpack", "category": "Objects" },
      { "name": "badge", "category": "Objects" },
      { "name": "badge-alert", "category": "Objects" },
      { "name": "badge-check", "category": "Objects" },
      { "name": "badge-dollar-sign", "category": "Money" },
      { "name": "badge-help", "category": "Objects" },
      { "name": "badge-info", "category": "Objects" },
      { "name": "badge-minus", "category": "Objects" },
      { "name": "badge-percent", "category": "Money" },
      { "name": "badge-plus", "category": "Objects" },
      { "name": "badge-x", "category": "Objects" },
      
      { "name": "baggage-claim", "category": "Travel" },
      { "name": "banana", "category": "Food & Beverage" },
      { "name": "banknote", "category": "Money" },
      { "name": "bar-chart", "category": "Charts" },
      { "name": "bar-chart-2", "category": "Charts" },
      { "name": "bar-chart-3", "category": "Charts" },
      { "name": "bar-chart-4", "category": "Charts" },
      { "name": "bar-chart-horizontal", "category": "Charts" },
      
      { "name": "baseline", "category": "Design" },
      { "name": "bath", "category": "Objects" },
      { "name": "battery", "category": "Devices" },
      { "name": "battery-charging", "category": "Devices" },
      { "name": "battery-full", "category": "Devices" },
      { "name": "battery-low", "category": "Devices" },
      { "name": "battery-medium", "category": "Devices" },
      { "name": "battery-warning", "category": "Devices" },
      
      { "name": "beaker", "category": "Objects" },
      { "name": "bean", "category": "Food & Beverage" },
      { "name": "bean-off", "category": "Food & Beverage" },
      { "name": "bed", "category": "Objects" },
      { "name": "bed-double", "category": "Objects" },
      { "name": "bed-single", "category": "Objects" },
      { "name": "beef", "category": "Food & Beverage" },
      { "name": "beer", "category": "Food & Beverage" },
      
      { "name": "bell", "category": "Communication" },
      { "name": "bell-dot", "category": "Communication" },
      { "name": "bell-minus", "category": "Communication" },
      { "name": "bell-off", "category": "Communication" },
      { "name": "bell-plus", "category": "Communication" },
      { "name": "bell-ring", "category": "Communication" },
      
      { "name": "bike", "category": "Transportation" },
      { "name": "binary", "category": "Text" },
      { "name": "biohazard", "category": "Medical" },
      { "name": "bird", "category": "Nature" },
      { "name": "bitcoin", "category": "Money" },
      
      { "name": "blinds", "category": "Objects" },
      { "name": "bluetooth", "category": "Connectivity" },
      { "name": "bluetooth-connected", "category": "Connectivity" },
      { "name": "bluetooth-off", "category": "Connectivity" },
      { "name": "bluetooth-searching", "category": "Connectivity" },
      
      { "name": "bold", "category": "Text" },
      { "name": "bomb", "category": "Objects" },
      { "name": "bone", "category": "Medical" },
      { "name": "book", "category": "Objects" },
      { "name": "book-a", "category": "Objects" },
      { "name": "book-audio", "category": "Objects" },
      { "name": "book-check", "category": "Objects" },
      { "name": "book-copy", "category": "Objects" },
      { "name": "book-down", "category": "Objects" },
      { "name": "book-headphones", "category": "Objects" },
      { "name": "book-heart", "category": "Objects" },
      { "name": "book-image", "category": "Objects" },
      { "name": "book-key", "category": "Objects" },
      { "name": "book-lock", "category": "Objects" },
      { "name": "book-marked", "category": "Objects" },
      { "name": "book-minus", "category": "Objects" },
      { "name": "book-open", "category": "Objects" },
      { "name": "book-open-check", "category": "Objects" },
      { "name": "book-open-text", "category": "Objects" },
      { "name": "book-plus", "category": "Objects" },
      { "name": "book-text", "category": "Objects" },
      { "name": "book-type", "category": "Objects" },
      { "name": "book-up", "category": "Objects" },
      { "name": "book-user", "category": "Objects" },
      { "name": "book-x", "category": "Objects" },
      
      { "name": "bookmark", "category": "Objects" },
      { "name": "bookmark-check", "category": "Objects" },
      { "name": "bookmark-minus", "category": "Objects" },
      { "name": "bookmark-plus", "category": "Objects" },
      { "name": "bookmark-x", "category": "Objects" },
      
      { "name": "bot", "category": "Technology" },
      { "name": "box", "category": "Objects" },
      { "name": "box-select", "category": "Design" },
      
      { "name": "boxes", "category": "Objects" },
      { "name": "braces", "category": "Text" },
      { "name": "brackets", "category": "Text" },
      { "name": "brain", "category": "Medical" },
      { "name": "brain-circuit", "category": "Medical" },
      { "name": "brain-cog", "category": "Medical" },
      
      { "name": "briefcase", "category": "Business" },
      { "name": "bring-to-front", "category": "Design" },
      { "name": "brush", "category": "Design" },
      { "name": "bug", "category": "Technology" },
      { "name": "bug-off", "category": "Technology" },
      { "name": "bug-play", "category": "Technology" },
      
      { "name": "building", "category": "Buildings" },
      { "name": "building-2", "category": "Buildings" },
      { "name": "bus", "category": "Transportation" },
      { "name": "bus-front", "category": "Transportation" },
      
      { "name": "cake", "category": "Food & Beverage" },
      { "name": "cake-slice", "category": "Food & Beverage" },
      { "name": "calculator", "category": "Devices" },
      { "name": "calendar", "category": "Time" },
      { "name": "calendar-check", "category": "Time" },
      { "name": "calendar-check-2", "category": "Time" },
      { "name": "calendar-clock", "category": "Time" },
      { "name": "calendar-days", "category": "Time" },
      { "name": "calendar-heart", "category": "Time" },
      { "name": "calendar-minus", "category": "Time" },
      { "name": "calendar-off", "category": "Time" },
      { "name": "calendar-plus", "category": "Time" },
      { "name": "calendar-range", "category": "Time" },
      { "name": "calendar-search", "category": "Time" },
      { "name": "calendar-x", "category": "Time" },
      { "name": "calendar-x-2", "category": "Time" },
      
      { "name": "camera", "category": "Photography" },
      { "name": "camera-off", "category": "Photography" },
      
      { "name": "car", "category": "Transportation" },
      { "name": "car-front", "category": "Transportation" },
      { "name": "carrot", "category": "Food & Beverage" },
      
      { "name": "case", "category": "Objects" },
      { "name": "case-lower", "category": "Text" },
      { "name": "case-sensitive", "category": "Text" },
      { "name": "case-upper", "category": "Text" },
      
      { "name": "cassette-tape", "category": "Media" },
      { "name": "cast", "category": "Devices" },
      
      { "name": "castle", "category": "Buildings" },
      { "name": "cat", "category": "Nature" },
      
      { "name": "check", "category": "Shapes" },
      { "name": "check-check", "category": "Shapes" },
      { "name": "check-circle", "category": "Shapes" },
      { "name": "check-circle-2", "category": "Shapes" },
      { "name": "check-square", "category": "Shapes" },
      { "name": "check-square-2", "category": "Shapes" },
      
      { "name": "chef-hat", "category": "Food & Beverage" },
      { "name": "cherry", "category": "Food & Beverage" },
      { "name": "chevron-down", "category": "Arrows" },
      { "name": "chevron-down-circle", "category": "Arrows" },
      { "name": "chevron-down-square", "category": "Arrows" },
      { "name": "chevron-first", "category": "Arrows" },
      { "name": "chevron-last", "category": "Arrows" },
      { "name": "chevron-left", "category": "Arrows" },
      { "name": "chevron-left-circle", "category": "Arrows" },
      { "name": "chevron-left-square", "category": "Arrows" },
      { "name": "chevron-right", "category": "Arrows" },
      { "name": "chevron-right-circle", "category": "Arrows" },
      { "name": "chevron-right-square", "category": "Arrows" },
      { "name": "chevron-up", "category": "Arrows" },
      { "name": "chevron-up-circle", "category": "Arrows" },
      { "name": "chevron-up-square", "category": "Arrows" },
      
      { "name": "chevrons-down", "category": "Arrows" },
      { "name": "chevrons-down-up", "category": "Arrows" },
      { "name": "chevrons-left", "category": "Arrows" },
      { "name": "chevrons-left-right", "category": "Arrows" },
      { "name": "chevrons-right", "category": "Arrows" },
      { "name": "chevrons-right-left", "category": "Arrows" },
      { "name": "chevrons-up", "category": "Arrows" },
      { "name": "chevrons-up-down", "category": "Arrows" },
      
      { "name": "chrome", "category": "Logos" },
      { "name": "church", "category": "Buildings" },
      { "name": "cigarette", "category": "Objects" },
      { "name": "cigarette-off", "category": "Objects" },
      
      { "name": "circle", "category": "Shapes" },
      { "name": "circle-dashed", "category": "Shapes" },
      { "name": "circle-dollar-sign", "category": "Money" },
      { "name": "circle-dot", "category": "Shapes" },
      { "name": "circle-dot-dashed", "category": "Shapes" },
      { "name": "circle-ellipsis", "category": "Shapes" },
      { "name": "circle-equal", "category": "Shapes" },
      { "name": "circle-off", "category": "Shapes" },
      { "name": "circle-slash", "category": "Shapes" },
      { "name": "circle-slash-2", "category": "Shapes" },
      { "name": "circle-user", "category": "Account" },
      { "name": "circle-user-round", "category": "Account" },
      
      { "name": "circuit-board", "category": "Technology" },
      { "name": "citrus", "category": "Food & Beverage" },
      
      { "name": "clapperboard", "category": "Media" },
      { "name": "clipboard", "category": "Files" },
      { "name": "clipboard-check", "category": "Files" },
      { "name": "clipboard-copy", "category": "Files" },
      { "name": "clipboard-edit", "category": "Files" },
      { "name": "clipboard-list", "category": "Files" },
      { "name": "clipboard-paste", "category": "Files" },
      { "name": "clipboard-signature", "category": "Files" },
      { "name": "clipboard-type", "category": "Files" },
      { "name": "clipboard-x", "category": "Files" },
      
      { "name": "clock", "category": "Time" },
      { "name": "clock-1", "category": "Time" },
      { "name": "clock-10", "category": "Time" },
      { "name": "clock-11", "category": "Time" },
      { "name": "clock-12", "category": "Time" },
      { "name": "clock-2", "category": "Time" },
      { "name": "clock-3", "category": "Time" },
      { "name": "clock-4", "category": "Time" },
      { "name": "clock-5", "category": "Time" },
      { "name": "clock-6", "category": "Time" },
      { "name": "clock-7", "category": "Time" },
      { "name": "clock-8", "category": "Time" },
      { "name": "clock-9", "category": "Time" },
      
      { "name": "cloud", "category": "Weather" },
      { "name": "cloud-cog", "category": "Weather" },
      { "name": "cloud-drizzle", "category": "Weather" },
      { "name": "cloud-fog", "category": "Weather" },
      { "name": "cloud-hail", "category": "Weather" },
      { "name": "cloud-lightning", "category": "Weather" },
      { "name": "cloud-moon", "category": "Weather" },
      { "name": "cloud-moon-rain", "category": "Weather" },
      { "name": "cloud-off", "category": "Weather" },
      { "name": "cloud-rain", "category": "Weather" },
      { "name": "cloud-rain-wind", "category": "Weather" },
      { "name": "cloud-snow", "category": "Weather" },
      { "name": "cloud-sun", "category": "Weather" },
      { "name": "cloud-sun-rain", "category": "Weather" },
      
      { "name": "cloudy", "category": "Weather" },
      { "name": "clover", "category": "Nature" },
      { "name": "club", "category": "Gaming" },
      { "name": "code", "category": "Text" },
      { "name": "code-2", "category": "Text" },
      { "name": "codepen", "category": "Logos" },
      { "name": "codesandbox", "category": "Logos" },
      { "name": "coffee", "category": "Food & Beverage" },
      { "name": "cog", "category": "Objects" },
      { "name": "coins", "category": "Money" },
      { "name": "columns", "category": "Design" },
      { "name": "columns-2", "category": "Design" },
      { "name": "columns-3", "category": "Design" },
      { "name": "columns-4", "category": "Design" },
      
      { "name": "combine", "category": "Design" },
      { "name": "command", "category": "Text" },
      { "name": "compass", "category": "Maps" },
      
      { "name": "component", "category": "Design" },
      { "name": "computer", "category": "Devices" },
      { "name": "concierge-bell", "category": "Objects" },
      { "name": "cone", "category": "Objects" },
      { "name": "construction", "category": "Tools" },
      
      { "name": "contact", "category": "Communication" },
      { "name": "contact-2", "category": "Communication" },
      { "name": "container", "category": "Objects" },
      { "name": "contrast", "category": "Design" },
      { "name": "cookie", "category": "Food & Beverage" },
      { "name": "copy", "category": "Files" },
      { "name": "copy-check", "category": "Files" },
      { "name": "copy-minus", "category": "Files" },
      { "name": "copy-plus", "category": "Files" },
      { "name": "copy-slash", "category": "Files" },
      { "name": "copy-x", "category": "Files" },
      
      { "name": "copyleft", "category": "Text" },
      { "name": "copyright", "category": "Text" },
      { "name": "corner-down-left", "category": "Arrows" },
      { "name": "corner-down-right", "category": "Arrows" },
      { "name": "corner-left-down", "category": "Arrows" },
      { "name": "corner-left-up", "category": "Arrows" },
      { "name": "corner-right-down", "category": "Arrows" },
      { "name": "corner-right-up", "category": "Arrows" },
      { "name": "corner-up-left", "category": "Arrows" },
      { "name": "corner-up-right", "category": "Arrows" },
      
      { "name": "cpu", "category": "Devices" },
      { "name": "creative-commons", "category": "Logos" },
      { "name": "credit-card", "category": "Money" },
      { "name": "croissant", "category": "Food & Beverage" },
      { "name": "crop", "category": "Design" },
      
      { "name": "cross", "category": "Shapes" },
      { "name": "crosshair", "category": "Design" },
      { "name": "crown", "category": "Objects" },
      { "name": "cuboid", "category": "Shapes" },
      
      { "name": "cup-soda", "category": "Food & Beverage" },
      { "name": "curly-braces", "category": "Text" },
      { "name": "currency", "category": "Money" },
      
      { "name": "cylinder", "category": "Shapes" },
      { "name": "database", "category": "Technology" },
      { "name": "database-backup", "category": "Technology" },
      { "name": "delete", "category": "Files" },
      
      { "name": "dessert", "category": "Food & Beverage" },
      { "name": "diamond", "category": "Shapes" },
      
      { "name": "dice-1", "category": "Gaming" },
      { "name": "dice-2", "category": "Gaming" },
      { "name": "dice-3", "category": "Gaming" },
      { "name": "dice-4", "category": "Gaming" },
      { "name": "dice-5", "category": "Gaming" },
      { "name": "dice-6", "category": "Gaming" },
      
      { "name": "dices", "category": "Gaming" },
      { "name": "diff", "category": "Files" },
      { "name": "disc", "category": "Media" },
      { "name": "disc-2", "category": "Media" },
      { "name": "disc-3", "category": "Media" },
      
      { "name": "divide", "category": "Text" },
      { "name": "divide-circle", "category": "Text" },
      { "name": "divide-square", "category": "Text" },
      
      { "name": "dna", "category": "Medical" },
      { "name": "dna-off", "category": "Medical" },
      { "name": "dog", "category": "Nature" },
      
      { "name": "dollar-sign", "category": "Money" },
      { "name": "donut", "category": "Food & Beverage" },
      { "name": "door-closed", "category": "Objects" },
      { "name": "door-open", "category": "Objects" },
      
      { "name": "dot", "category": "Shapes" },
      { "name": "download", "category": "Files" },
      { "name": "download-cloud", "category": "Files" },
      
      { "name": "dribbble", "category": "Logos" },
      { "name": "droplet", "category": "Weather" },
      { "name": "droplets", "category": "Weather" },
      { "name": "drumstick", "category": "Food & Beverage" },
      
      { "name": "dumbbell", "category": "Sports" },
      { "name": "ear", "category": "Accessibility" },
      { "name": "ear-off", "category": "Accessibility" },
      
      { "name": "egg", "category": "Food & Beverage" },
      { "name": "egg-fried", "category": "Food & Beverage" },
      { "name": "egg-off", "category": "Food & Beverage" },
      
      { "name": "equal", "category": "Text" },
      { "name": "equal-not", "category": "Text" },
      { "name": "eraser", "category": "Design" },
      
      { "name": "euro", "category": "Money" },
      { "name": "expand", "category": "Design" },
      
      { "name": "external-link", "category": "Arrows" },
      { "name": "eye", "category": "Accessibility" },
      { "name": "eye-off", "category": "Accessibility" },
      
      { "name": "facebook", "category": "Logos" },
      { "name": "factory", "category": "Buildings" },
      
      { "name": "fan", "category": "Objects" },
      { "name": "fast-forward", "category": "Media" },
      { "name": "feather", "category": "Objects" },
      
      { "name": "figma", "category": "Logos" },
      { "name": "file", "category": "Files" },
      { "name": "file-archive", "category": "Files" },
      { "name": "file-audio", "category": "Files" },
      { "name": "file-audio-2", "category": "Files" },
      { "name": "file-axis-3d", "category": "Files" },
      { "name": "file-badge", "category": "Files" },
      { "name": "file-badge-2", "category": "Files" },
      { "name": "file-bar-chart", "category": "Files" },
      { "name": "file-bar-chart-2", "category": "Files" },
      { "name": "file-box", "category": "Files" },
      { "name": "file-check", "category": "Files" },
      { "name": "file-check-2", "category": "Files" },
      { "name": "file-clock", "category": "Files" },
      { "name": "file-code", "category": "Files" },
      { "name": "file-cog", "category": "Files" },
      { "name": "file-cog-2", "category": "Files" },
      { "name": "file-diff", "category": "Files" },
      { "name": "file-digit", "category": "Files" },
      { "name": "file-down", "category": "Files" },
      { "name": "file-edit", "category": "Files" },
      { "name": "file-heart", "category": "Files" },
      { "name": "file-image", "category": "Files" },
      { "name": "file-input", "category": "Files" },
      { "name": "file-json", "category": "Files" },
      { "name": "file-json-2", "category": "Files" },
      { "name": "file-key", "category": "Files" },
      { "name": "file-key-2", "category": "Files" },
      { "name": "file-line-chart", "category": "Files" },
      { "name": "file-lock", "category": "Files" },
      { "name": "file-lock-2", "category": "Files" },
      { "name": "file-minus", "category": "Files" },
      { "name": "file-minus-2", "category": "Files" },
      { "name": "file-output", "category": "Files" },
      { "name": "file-pie-chart", "category": "Files" },
      { "name": "file-plus", "category": "Files" },
      { "name": "file-plus-2", "category": "Files" },
      { "name": "file-question", "category": "Files" },
      { "name": "file-scan", "category": "Files" },
      { "name": "file-search", "category": "Files" },
      { "name": "file-search-2", "category": "Files" },
      { "name": "file-signature", "category": "Files" },
      { "name": "file-spreadsheet", "category": "Files" },
      { "name": "file-stack", "category": "Files" },
      { "name": "file-symlink", "category": "Files" },
      { "name": "file-terminal", "category": "Files" },
      { "name": "file-text", "category": "Files" },
      { "name": "file-type", "category": "Files" },
      { "name": "file-type-2", "category": "Files" },
      { "name": "file-up", "category": "Files" },
      { "name": "file-video", "category": "Files" },
      { "name": "file-video-2", "category": "Files" },
      { "name": "file-volume", "category": "Files" },
      { "name": "file-volume-2", "category": "Files" },
      { "name": "file-warning", "category": "Files" },  
      { "name": "file-volume-2", "category": "Files" },
      { "name": "file-warning", "category": "Files" },
      { "name": "file-x", "category": "Files" },
      { "name": "file-x-2", "category": "Files" },
      
      { "name": "files", "category": "Files" },
      { "name": "film", "category": "Media" },
      { "name": "filter", "category": "Design" },
      { "name": "filter-x", "category": "Design" },
      
      { "name": "fingerprint", "category": "Security" },
      { "name": "fish", "category": "Nature" },
      { "name": "fish-off", "category": "Nature" },
      { "name": "fish-symbol", "category": "Shapes" },
      
      { "name": "flag", "category": "Maps" },
      { "name": "flag-off", "category": "Maps" },
      { "name": "flag-triangle-left", "category": "Maps" },
      { "name": "flag-triangle-right", "category": "Maps" },
      
      { "name": "flame", "category": "Weather" },
      { "name": "flashlight", "category": "Objects" },
      { "name": "flashlight-off", "category": "Objects" },
      
      { "name": "flask-conical", "category": "Objects" },
      { "name": "flask-conical-off", "category": "Objects" },
      { "name": "flask-round", "category": "Objects" },
      
      { "name": "flip-horizontal", "category": "Design" },
      { "name": "flip-horizontal-2", "category": "Design" },
      { "name": "flip-vertical", "category": "Design" },
      { "name": "flip-vertical-2", "category": "Design" },
      
      { "name": "flower", "category": "Nature" },
      { "name": "flower-2", "category": "Nature" },
      { "name": "focus", "category": "Photography" },
      
      { "name": "folder", "category": "Files" },
      { "name": "folder-archive", "category": "Files" },
      { "name": "folder-check", "category": "Files" },
      { "name": "folder-clock", "category": "Files" },
      { "name": "folder-closed", "category": "Files" },
      { "name": "folder-cog", "category": "Files" },
      { "name": "folder-cog-2", "category": "Files" },
      { "name": "folder-dot", "category": "Files" },
      { "name": "folder-down", "category": "Files" },
      { "name": "folder-edit", "category": "Files" },
      { "name": "folder-heart", "category": "Files" },
      { "name": "folder-input", "category": "Files" },
      { "name": "folder-key", "category": "Files" },
      { "name": "folder-lock", "category": "Files" },
      { "name": "folder-minus", "category": "Files" },
      { "name": "folder-open", "category": "Files" },
      { "name": "folder-output", "category": "Files" },
      { "name": "folder-plus", "category": "Files" },
      { "name": "folder-search", "category": "Files" },
      { "name": "folder-search-2", "category": "Files" },
      { "name": "folder-symlink", "category": "Files" },
      { "name": "folder-sync", "category": "Files" },
      { "name": "folder-tree", "category": "Files" },
      { "name": "folder-up", "category": "Files" },
      { "name": "folder-x", "category": "Files" }
    ]
  };
  